name: Live Market Data Sync

on:
  # 1. Scheduled run (Runs every weekday at 3:40 PM IST / 11:10 AM UTC)
  schedule:
    # CRON Expression: M H D M W
    # Runs at 11:10 UTC (3:40 PM IST) on days 1-5 (Mon-Fri)
    - cron: '10 11 * * 1-5' 

  # 2. Manual trigger (Allows you to run it anytime manually from the GitHub UI)
  workflow_dispatch:
    
# FIX: Add permissions to allow the bot to commit and push changes back to the repository
permissions:
  contents: write

jobs:
  update-market-data:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Use default token, which now has write permission
          token: ${{ secrets.GITHUB_TOKEN }} 
          
      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install necessary dependencies (for node-fetch)
      - name: Install Dependencies
        run: npm install 

      # Step 4: Run the data fetching script (No API Key needed)
      - name: Fetch and Process Live Data
        run: node fetch_live_data.js

      # Step 5: Commit and push the updated marketdata.json file
      - name: Commit Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Data Sync: Auto-updated marketdata.json from NSE"
          branch: main # Change to your primary branch name if different
